id: PBB4A7C57
initial_creation_type: ocr
source_metadata:
  volumes:
    f22fbd43b25c43e59432ac0e26bc9653:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: འཇམ་པ་ཁྲོ་བོར་སྒྲུབ་པ།
      total_pages: 1902
      volume_number: 26
