id: D1444E14A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-02-24T10:25:01+00:00'
last_modified: '2022-05-26T11:26:36.765798+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    3bca:
      image_group_id: I1PD95871
      title: འཇམ་པ་ཁྲོ་བོར་སྒྲུབ་པ།
      total_pages: 1902
      order: 26
      base_file: 3bca.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
